CREATE TABLE training_plans (
    day_of_week VARCHAR(9) PRIMARY KEY,
    content_json TEXT NOT NULL
);

INSERT INTO training_plans (day_of_week, content_json) VALUES
('MONDAY', '{"type":"rest","title":"Rest","subtitle":"Recovery day","warmup":[],"exercises":[],"guardrails":["This is an intentional rest day.","Do not make up missed training automatically.","Prioritize recovery and sleep."],"optional":["Easy walking","Light mobility","Easy Zone 2 cardio if desired"]}'),
('TUESDAY', '{"type":"workout","title":"Push","subtitle":"Chest, shoulders, triceps","warmup":["5 min easy treadmill or bike","1–2 lighter ramp-up sets before the first press"],"exercises":[{"name":"Machine Chest Press","sets":2,"reps":"6–10","rir":"3–4","rest":"2 min"},{"name":"Incline Dumbbell Press","sets":2,"reps":"8–12","rir":"3–4","rest":"2 min"},{"name":"Seated Machine Shoulder Press","sets":2,"reps":"8–12","rir":"3","rest":"90 sec"},{"name":"Cable or Machine Lateral Raise","sets":2,"reps":"12–18","rir":"3","rest":"60 sec"},{"name":"Rope Pressdown","sets":2,"reps":"10–15","rir":"3","rest":"60 sec"}],"guardrails":["First ramp week stays at 2 work sets.","No failure sets.","Stop if dizziness or unusual breathlessness appears."],"optional":[]}'),
('WEDNESDAY', '{"type":"workout","title":"Pull","subtitle":"Back, rear delts, biceps","warmup":["5 min easy cardio","Very light cable row x 12","Pulldown technique ramp-up set"],"exercises":[{"name":"Lat Pulldown","sets":2,"reps":"8-12","rir":"3-4","rest":"2 min","notes":"Pause near chest. Avoid turning it into a lean-back pull."},{"name":"Chest-Supported Row","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Neutral-Grip Pulldown","sets":2,"reps":"10-12","rir":"3","rest":"90 sec"},{"name":"Reverse Pec Deck","sets":2,"reps":"12-18","rir":"3","rest":"60 sec"},{"name":"Cable Curl","sets":2,"reps":"10-15","rir":"3","rest":"75 sec"}],"guardrails":["Prioritize clean back connection over load.","No grip/carry work if gym rules block it."],"optional":[]}'),
('THURSDAY', '{"type":"workout","title":"Legs + Core","subtitle":"Stable lower body and core","warmup":["5 min easy bike or treadmill","Supported sit-to-stand x 8","1-2 light ramp-up sets on leg press"],"exercises":[{"name":"Leg Press","sets":2,"reps":"8-12","rir":"3-4","rest":"2-3 min","notes":"Use comfortable depth only."},{"name":"Seated Leg Curl","sets":2,"reps":"10-15","rir":"3","rest":"90 sec"},{"name":"Supported Short-Range Split Squat","sets":2,"reps":"8-10 / side","rir":"4","rest":"2 min","notes":"Swap to leg press if knee pain or instability repeats."},{"name":"Hip Thrust Machine","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Pallof Press","sets":2,"reps":"8-12 / side","rest":"60 sec"}],"guardrails":["No loaded hinging if back symptoms recur.","No painful deep squat range."],"optional":[]}'),
('FRIDAY', '{"type":"rest","title":"Rest","subtitle":"Recovery / sleep protection","warmup":[],"exercises":[],"guardrails":["This is a recovery day, not a missed lifting slot.","No hard session after under 6 hours of sleep.","Do not automatically make up missed work."],"optional":["Easy walk after work","Easy Zone 2 cardio · 0–30 min · Easy effort"]}'),
('SATURDAY', '{"type":"workout","title":"Upper","subtitle":"Upper body plus skill practice","warmup":["5 min easy cardio","Light row and press ramp-up sets"],"exercises":[{"name":"Incline Dumbbell Press","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Seated Cable Row","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Lat Pulldown","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Machine Chest Press","sets":2,"reps":"8-12","rir":"3","rest":"90 sec"},{"name":"Lateral Raise","sets":2,"reps":"12-18","rir":"3","rest":"60 sec"},{"name":"Rope Pressdown","sets":2,"reps":"10-15","rir":"3","rest":"60 sec"},{"name":"Cable Curl","sets":2,"reps":"10-15","rir":"3","rest":"60 sec"}],"guardrails":["Keep skill reps crisp.","Do not chase failure."],"optional":[]}'),
('SUNDAY', '{"type":"workout","title":"Lower","subtitle":"Lower body strength and controlled movement","warmup":["5 min easy bike or treadmill","Supported sit-to-stand x 8","1-2 light leg press ramp-up sets"],"exercises":[{"name":"Leg Press","sets":2,"reps":"8-12","rir":"3","rest":"2-3 min"},{"name":"Seated Leg Curl","sets":2,"reps":"10-15","rir":"3","rest":"90 sec"},{"name":"Hip Thrust Machine","sets":2,"reps":"8-12","rir":"3","rest":"2 min"},{"name":"Supported Split Squat","sets":2,"reps":"8-10 / side","rir":"3-4","rest":"2 min"},{"name":"Pallof Press","sets":2,"reps":"8-12 / side","rest":"60 sec"}],"guardrails":["Use controlled ranges of motion.","Do not train through knee or back pain.","Do not chase failure."],"optional":[]}');
